version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: minimal-shop-db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_apple_123
      POSTGRES_DB: minimal_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: minimal-shop-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@apple.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: